name: CI ReUse Dev
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
      docker_build:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: npm install
        name: Download NodeJS Dependencies
        if: inputs.appType == 'nodejs'
      - run: mvn package
        name: Download Maven Dependencies
        if: inputs.appType == 'maven'
      - name: Import Secrets
        if: inputs.docker_build == 'true'
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-int.mydevops.shop:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
      - name: Docker Build
        if: inputs.docker_build == 'true'
        run: |
          az login --service-principal --username "${ARM_CLIENT_ID}" --password "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          TOKEN=$(az acr login -n devopshop --expose-token --query accessToken -o tsv)
          echo $TOKEN | docker login devopshop.azurecr.io -u 00000000-0000-0000-0000-000000000000 --password-stdin
          docker build -t devopshop.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }} .
          docker push devopshop.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }}
  

